/**
 * 内部消息类型枚举
 * 用于 Popup ↔ Background, Content Script ↔ Background 通信
 */
export const MSG = {
  // === 钱包管理 ===
  CREATE_WALLET: 'CREATE_WALLET',
  IMPORT_WALLET: 'IMPORT_WALLET',
  UNLOCK_WALLET: 'UNLOCK_WALLET',
  LOCK_WALLET: 'LOCK_WALLET',
  GET_WALLET_STATE: 'GET_WALLET_STATE',

  // === 账户管理 ===
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  SELECT_ACCOUNT: 'SELECT_ACCOUNT',
  EXPORT_MNEMONIC: 'EXPORT_MNEMONIC',

  // === 网络 ===
  GET_NETWORK: 'GET_NETWORK',
  SWITCH_NETWORK: 'SWITCH_NETWORK',
  GET_BALANCE: 'GET_BALANCE',

  // === 交易 ===
  SEND_TRANSACTION: 'SEND_TRANSACTION',
  ESTIMATE_GAS: 'ESTIMATE_GAS',
  GET_GAS_PRICE: 'GET_GAS_PRICE',

  // === dApp 通信 ===
  DAPP_REQUEST: 'DAPP_REQUEST',
  DAPP_RESPONSE: 'DAPP_RESPONSE',

  // === dApp 授权 ===
  APPROVE_CONNECTION: 'APPROVE_CONNECTION',
  REJECT_CONNECTION: 'REJECT_CONNECTION',
  APPROVE_TRANSACTION: 'APPROVE_TRANSACTION',
  REJECT_TRANSACTION: 'REJECT_TRANSACTION',
  GET_PENDING_REQUEST: 'GET_PENDING_REQUEST',

  // === 事件 ===
  ACCOUNTS_CHANGED: 'ACCOUNTS_CHANGED',
  CHAIN_CHANGED: 'CHAIN_CHANGED',
};

/**
 * 钱包状态枚举
 */
export const WALLET_STATE = {
  UNINITIALIZED: 'UNINITIALIZED',
  LOCKED: 'LOCKED',
  UNLOCKED: 'UNLOCKED',
};

/**
 * Inpage ↔ Content Script 消息通道标识
 */
export const CHANNEL = {
  INPAGE_TO_CONTENT: 'QIANBAO_INPAGE_TO_CONTENT',
  CONTENT_TO_INPAGE: 'QIANBAO_CONTENT_TO_INPAGE',
};
